# Generated by Django 5.0.6 on 2024-07-16 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='app.category'),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionheader', models.TextField(default='Description')),
                ('text', models.TextField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='app.place')),
            ],
        ),
    ]
