# Generated by Django 5.0.6 on 2024-07-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_place_description_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='descriptionheader',
            field=models.TextField(default='Description'),
        ),
    ]
