# Generated by Django 5.0.6 on 2024-07-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_description_descriptionheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', upload_to='place_pics'),
        ),
    ]
