# Generated by Django 5.0.6 on 2024-07-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(default='default.png', upload_to='place_pics'),
        ),
    ]
