# Generated by Django 5.0.6 on 2024-07-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customuser_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user',
            new_name='username',
        ),
    ]
